name: Generate Directory Markdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository and fetch all branches
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # ensure all branches are fetched

      # Run the directory tree generator
      - name: Run Directory Tree Generator
        uses: DenizAltunkapan/directory-tree-generator@v2
        with:
          path: "backend,frontend"
          extensions: ".java,.html,.ts,.scss"
          show-extensions: true

      # Commit changes and push to a separate branch
      - name: Commit and push changes
        run: |
          # Configure Git user for commits (GitHub Actions bot)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Update local main branch before creating the directory branch
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          # Create or reset the directory branch
          git checkout -B directory

          # Stage and commit changes if any
          git add DIRECTORY.md
          git diff --cached --quiet || git commit -m "Update DIRECTORY.md"

          # Push to the directory branch
          git push origin directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
