name: Generate Directory Markdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run Directory Tree Generator
        uses: DenizAltunkapan/directory-tree-generator@v2
        with:
          path: "backend,frontend"
          extensions: ".java,.html,.ts,.scss"
          show-extensions: true

      - name: Commit and push changes
        run: |
          git config --global user.name "DenizAltunkapan"
          git config --global user.email "deniz.altunkapan@outlook.com"
          git add DIRECTORY.md
          git diff --cached --quiet || git commit -m "Update DIRECTORY.md"
          git push https://x-access-token:${{ secrets.Directory_Token }}@github.com/Vault-Web/password-manager.git main
        env:
          GITHUB_TOKEN: ${{ secrets.Directory_Token }}
