name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # - name: Run ESLint
      #   working-directory: frontend
      #   run: npm run lint

      - name: Check formatting with Prettier
        working-directory: frontend
        run: npm run prettier:check

      - name: Build project
        working-directory: frontend
        run: npm run build
